settings:
  title: 'Status Page'
  url: 'https://status.burtnet.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: email-imap
    name: MXroute Email - IMAP
    description: 'MXroute Email - IMAP'
    url: 'tcp://moose.mxrouting.net:993'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: email-smtp
    name: MXroute Email - SMTP
    description: 'MXroute Email - SMTP'
    url: 'tcp://moose.mxrouting.net:465'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: webapp-actual # unique identifier
    name: WebApp - Actual
    description: 'Actual @ Hostinger VPS' # default=empty
    url: 'https://finance.burtnet.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: webapp-portainer
    name: WebApp - Portainer
    description: 'Portainer @ Hostinger VPS'
    url: 'https://docker.burtnet.xyz/'
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: webapp-shlink
    name: WebApp - Shlink
    description: 'Shlink @ Hostinger VPS'
    url: 'https://go.burtnet.xyz/uptimeping'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: gw-batcave-viewqwest
    name: GW - BaTcave - Viewqwest
    description: 'Primary uplink (Viewqwest) from BaTcave'
    url: 'icmp-ping://gw1.burtnet.xyz'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: gw-batcave-m1
    name: GW - BaTcave - M1
    description: 'Secondary uplink (M1) from BaTcave'
    url: 'icmp-ping://gw2.burtnet.xyz'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: gw-onan
    name: GW - Onan
    description: 'Uplink (M1) from Onan'
    url: 'icmp-ping://d9z9q0syxnd.d.firewalla.org'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
