settings:
  title: 'Status Page'
  url: 'https://status.burtnet.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: doh1 # unique identifier
    name: AdGuard Home - DoH 1
    description: 'BurtNet DoH 1 - powered by AdGuard Home' # default=empty
    url: 'https://dns1.burtnet.xyz/dns-query?dns=AAABAAABAAAAAAAAB2J1cnRuZXQDeHl6AAABAAEK' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: doh2 # unique identifier
    name: AdGuard Home - DoH 2
    description: 'BurtNet DoH 2 - powered by AdGuard Home' # default=empty
    url: 'https://dns2.burtnet.xyz/dns-query?dns=AAABAAABAAAAAAAAB2J1cnRuZXQDeHl6AAABAAEK' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: webapp-shlink
    name: WebApp - Shlink
    description: 'Shlink @ Hostinger VPS'
    url: 'https://go.burtnet.xyz/uptimeping'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
